FROM php:8.1-apache

# Habilitar mod_rewrite para apache
RUN a2enmod rewrite

# Instalar extensiones PDO MySQL
RUN docker-php-ext-install pdo pdo_mysql

# Ajustar los permisos
RUN chown -W www-data:www-data /var/www/html
